"""
Seed script for Akiya Tracker - populates the database with realistic
Japanese abandoned house (空き家) listings across depopulated prefectures.
"""
import json
from datetime import datetime, timedelta
from sqlmodel import Session, select
from database import create_db_and_tables, engine
from models import Property, PropertyType, PropertyStatus, PropertyCondition


SEED_DATA = [
    # ─── SHIMANE (島根) ───────────────────────────────────────────────────────
    {
        "title_jp": "茅葺き屋根の古民家 - 奥出雲町",
        "title_en": "Thatched-Roof Kominka in Okuizumo",
        "prefecture": "島根県",
        "municipality": "奥出雲町",
        "village_name": "仁多",
        "property_type": PropertyType.kominka,
        "status": PropertyStatus.available,
        "price_jpy": 500_000,
        "land_area_m2": 820.0,
        "building_area_m2": 145.0,
        "year_built": 1923,
        "condition": PropertyCondition.major_renovation,
        "distance_to_station_km": 12.5,
        "distance_to_convenience_store_km": 8.2,
        "has_akiya_bank_listing": True,
        "akiya_bank_url": "https://www.akiya-kankou.jp/shimane/",
        "municipal_subsidy_jpy": 1_500_000,
        "tags": ["thatched_roof", "mountain_view", "rice_fields", "traditional_irori", "well_water", "kominka"],
        "description": "築100年を超える茅葺き屋根の古民家。囲炉裏・土間・縁側を完備。奥出雲の山々に囲まれた静寂な環境。自給自足生活に最適。町の移住支援補助金対象物件。",
        "notes": "屋根の葺き替えが必要。構造材は良好。地元大工による修繕見積もり可能。",
        "latitude": 35.1833,
        "longitude": 133.0167,
        "population_decline_pct": 42.3,
    },
    {
        "title_jp": "山間の農家住宅 - 津和野町",
        "title_en": "Mountain Farmhouse in Tsuwano",
        "prefecture": "島根県",
        "municipality": "津和野町",
        "village_name": "左鐙",
        "property_type": PropertyType.noka,
        "status": PropertyStatus.available,
        "price_jpy": 1_200_000,
        "land_area_m2": 1200.0,
        "building_area_m2": 110.0,
        "year_built": 1951,
        "condition": PropertyCondition.renovation_needed,
        "distance_to_station_km": 6.0,
        "distance_to_convenience_store_km": 5.5,
        "has_akiya_bank_listing": True,
        "akiya_bank_url": "https://www.akiya-kankou.jp/shimane/",
        "municipal_subsidy_jpy": 800_000,
        "tags": ["mountain_view", "river_nearby", "large_garden", "koi_pond", "storehouse"],
        "description": "津和野川沿いの農家住宅。敷地内に蔵・納屋あり。小京都・津和野の中心部まで車で15分。SL列車の走る風光明媚なエリア。",
        "notes": "水回りの更新が必要。蔵は状態良好。",
        "latitude": 34.4667,
        "longitude": 131.7667,
        "population_decline_pct": 38.1,
    },
    # ─── KOCHI (高知) ────────────────────────────────────────────────────────
    {
        "title_jp": "無料空き家 - 人口89人の限界集落",
        "title_en": "Free Akiya in Remote Village (Pop. 89)",
        "prefecture": "高知県",
        "municipality": "大豊町",
        "village_name": "杉ヶ市",
        "property_type": PropertyType.akiya,
        "status": PropertyStatus.available,
        "price_jpy": 0,
        "land_area_m2": 430.0,
        "building_area_m2": 78.0,
        "year_built": 1965,
        "condition": PropertyCondition.major_renovation,
        "distance_to_station_km": 22.0,
        "distance_to_convenience_store_km": 18.0,
        "has_akiya_bank_listing": True,
        "akiya_bank_url": "https://kochi-akiya.jp/",
        "municipal_subsidy_jpy": 2_000_000,
        "tags": ["free_property", "mountain_village", "river_view", "remote", "off_grid_potential", "sugi_forest"],
        "description": "現在の人口わずか89人の限界集落にある空き家。無料で譲渡。高知県の補助金制度により最大200万円の改修支援あり。吉野川源流の清流沿い。山暮らし・自然農を始めたい方に。",
        "notes": "電気・水道は引き込み済み。プロパンガス。冬季は積雪あり。軽トラ必須の立地。",
        "latitude": 33.8167,
        "longitude": 133.7000,
        "population_decline_pct": 67.8,
    },
    {
        "title_jp": "四万十川沿いの古民家",
        "title_en": "Kominka Along the Shimanto River",
        "prefecture": "高知県",
        "municipality": "四万十市",
        "village_name": "西土佐",
        "property_type": PropertyType.kominka,
        "status": PropertyStatus.available,
        "price_jpy": 800_000,
        "land_area_m2": 650.0,
        "building_area_m2": 98.0,
        "year_built": 1938,
        "condition": PropertyCondition.renovation_needed,
        "distance_to_station_km": 4.5,
        "distance_to_convenience_store_km": 3.2,
        "has_akiya_bank_listing": True,
        "akiya_bank_url": "https://kochi-akiya.jp/",
        "municipal_subsidy_jpy": 1_200_000,
        "tags": ["river_view", "shimanto_river", "fishing", "canoe_kayak", "traditional_architecture", "engawa"],
        "description": "日本最後の清流・四万十川を望む古民家。縁側から川の眺めが楽しめる。鮎釣り・カヌーのメッカ。古民家カフェやゲストハウスへの転用実績あり。",
        "notes": "床の一部補修が必要。屋根は10年前に修繕済み。",
        "latitude": 32.9833,
        "longitude": 132.8333,
        "population_decline_pct": 29.4,
    },
    {
        "title_jp": "土佐の山里 農家物件",
        "title_en": "Tosa Highland Farmstead",
        "prefecture": "高知県",
        "municipality": "本山町",
        "village_name": "吉野",
        "property_type": PropertyType.noka,
        "status": PropertyStatus.negotiating,
        "price_jpy": 300_000,
        "land_area_m2": 2500.0,
        "building_area_m2": 125.0,
        "year_built": 1948,
        "condition": PropertyCondition.major_renovation,
        "distance_to_station_km": 15.0,
        "distance_to_convenience_store_km": 10.0,
        "has_akiya_bank_listing": False,
        "akiya_bank_url": None,
        "municipal_subsidy_jpy": 1_000_000,
        "tags": ["rice_paddies", "vegetable_fields", "mountain_spring", "solar_potential", "large_land"],
        "description": "広大な農地付きの農家物件。田んぼ・畑・山林含む約2500㎡。山清水あり。自給農業を実践したい移住者向け。",
        "notes": "現在交渉中。農地法の許可が必要。農業委員会への届け出要。",
        "latitude": 33.7500,
        "longitude": 133.6167,
        "population_decline_pct": 51.2,
    },
    # ─── AKITA (秋田) ────────────────────────────────────────────────────────
    {
        "title_jp": "秋田杉の古民家 - 西木村",
        "title_en": "Akita Cedar Kominka in Nishiki Village",
        "prefecture": "秋田県",
        "municipality": "仙北市",
        "village_name": "西木",
        "property_type": PropertyType.kominka,
        "status": PropertyStatus.available,
        "price_jpy": 2_500_000,
        "land_area_m2": 950.0,
        "building_area_m2": 180.0,
        "year_built": 1910,
        "condition": PropertyCondition.renovation_needed,
        "distance_to_station_km": 18.0,
        "distance_to_convenience_store_km": 12.0,
        "has_akiya_bank_listing": True,
        "akiya_bank_url": "https://akita-akiya.jp/",
        "municipal_subsidy_jpy": 2_000_000,
        "tags": ["akita_cedar", "snow_country", "traditional_architecture", "onsen_nearby", "kakunodate_access", "large_kominka"],
        "description": "樹齢100年超の秋田杉を使った重厚な古民家。角館武家屋敷まで車20分。田沢湖・乳頭温泉も近い。豪雪地帯のため断熱改修が必要だが、構造体は非常に良好。",
        "notes": "屋根・断熱・水回りの改修を推奨。補助金申請サポートあり。",
        "latitude": 39.7000,
        "longitude": 140.5500,
        "population_decline_pct": 44.6,
    },
    {
        "title_jp": "廃校近くの農家 - 東成瀬村",
        "title_en": "Farmhouse Near Closed School, Higashinaruse",
        "prefecture": "秋田県",
        "municipality": "東成瀬村",
        "village_name": "椿川",
        "property_type": PropertyType.noka,
        "status": PropertyStatus.available,
        "price_jpy": 0,
        "land_area_m2": 1800.0,
        "building_area_m2": 140.0,
        "year_built": 1958,
        "condition": PropertyCondition.major_renovation,
        "distance_to_station_km": 35.0,
        "distance_to_convenience_store_km": 20.0,
        "has_akiya_bank_listing": True,
        "akiya_bank_url": "https://akita-akiya.jp/",
        "municipal_subsidy_jpy": 2_500_000,
        "tags": ["free_property", "snowfall_heavy", "rice_paddies", "mountain_village", "depopulated", "closed_school_nearby"],
        "description": "秋田県最小の村・東成瀬村の無料農家物件。廃校となった小学校に隣接。豊富な降雪量（年間積雪3m超）を活かしたスキーリゾートへのアクセスも良好。",
        "notes": "除雪設備（融雪槽）付き。重油ボイラー暖房。改修費用補助最大250万円。",
        "latitude": 39.1333,
        "longitude": 140.7167,
        "population_decline_pct": 59.3,
    },
    # ─── NAGANO (長野) ───────────────────────────────────────────────────────
    {
        "title_jp": "信州の山荘 - 棚田と古民家",
        "title_en": "Shinshu Mountain Farmhouse with Terraced Rice Fields",
        "prefecture": "長野県",
        "municipality": "飯田市",
        "village_name": "上村",
        "property_type": PropertyType.noka,
        "status": PropertyStatus.available,
        "price_jpy": 1_800_000,
        "land_area_m2": 3200.0,
        "building_area_m2": 165.0,
        "year_built": 1935,
        "condition": PropertyCondition.renovation_needed,
        "distance_to_station_km": 25.0,
        "distance_to_convenience_store_km": 15.0,
        "has_akiya_bank_listing": True,
        "akiya_bank_url": "https://nagano-akiya.jp/",
        "municipal_subsidy_jpy": 1_500_000,
        "tags": ["terraced_rice_fields", "mountain_view", "southern_alps_view", "traditional_irori", "apple_orchard", "forest_land"],
        "description": "南アルプスを望む棚田付き古民家。りんご・なし・柿の果樹園あり。囲炉裏・土間・縁側が残る伝統的な農家建築。遠山郷の秘境感あふれる立地。民泊・農家レストランへの転用可能性大。",
        "notes": "2012年に屋根を一部修繕。薪ストーブ設置済み。",
        "latitude": 35.3167,
        "longitude": 137.9333,
        "population_decline_pct": 46.7,
    },
    {
        "title_jp": "戸隠山麓の空き家",
        "title_en": "Akiya at the Foot of Mt. Togakushi",
        "prefecture": "長野県",
        "municipality": "長野市",
        "village_name": "戸隠",
        "property_type": PropertyType.akiya,
        "status": PropertyStatus.available,
        "price_jpy": 3_500_000,
        "land_area_m2": 480.0,
        "building_area_m2": 88.0,
        "year_built": 1972,
        "condition": PropertyCondition.livable,
        "distance_to_station_km": 30.0,
        "distance_to_convenience_store_km": 5.0,
        "has_akiya_bank_listing": True,
        "akiya_bank_url": "https://nagano-akiya.jp/",
        "municipal_subsidy_jpy": 500_000,
        "tags": ["mountain_view", "ski_resort_nearby", "soba_village", "shrine_access", "livable_condition", "nature"],
        "description": "戸隠神社・戸隠スキー場まで徒歩圏内。蕎麦の名産地として知られる戸隠高原の空き家。改修なしで即入居可能。長野市中心部まで約1時間。",
        "notes": "2020年まで居住。設備は古いが機能する。",
        "latitude": 36.7667,
        "longitude": 137.9000,
        "population_decline_pct": 22.1,
    },
    # ─── TOKUSHIMA (徳島) ────────────────────────────────────────────────────
    {
        "title_jp": "廃業した酒蔵 - 三好市",
        "title_en": "Abandoned Sake Brewery in Miyoshi City",
        "prefecture": "徳島県",
        "municipality": "三好市",
        "village_name": "池田",
        "property_type": PropertyType.kominka,
        "status": PropertyStatus.available,
        "price_jpy": 4_500_000,
        "land_area_m2": 720.0,
        "building_area_m2": 320.0,
        "year_built": 1905,
        "condition": PropertyCondition.renovation_needed,
        "distance_to_station_km": 0.8,
        "distance_to_convenience_store_km": 0.5,
        "has_akiya_bank_listing": True,
        "akiya_bank_url": "https://tokushima-akiya.jp/",
        "municipal_subsidy_jpy": 3_000_000,
        "tags": ["sake_brewery", "large_building", "station_close", "historic_building", "commercial_potential", "yoshino_river"],
        "description": "大正時代創業の酒蔵跡。吉野川に面した歴史的建造物。醸造設備の一部残存。広大な土蔵・仕込み蔵をシェアオフィス・ホテル・レストランへの転用事例多数。三好市の移住支援対象物件。",
        "notes": "建築士による事前調査を推奨。文化財指定なし。商業利用可能。",
        "latitude": 34.0167,
        "longitude": 133.8167,
        "population_decline_pct": 35.8,
    },
    {
        "title_jp": "祖谷渓の茅葺き民家",
        "title_en": "Thatched Farmhouse in Iya Valley",
        "prefecture": "徳島県",
        "municipality": "三好市",
        "village_name": "西祖谷山村",
        "property_type": PropertyType.kominka,
        "status": PropertyStatus.reserved,
        "price_jpy": 1_000_000,
        "land_area_m2": 560.0,
        "building_area_m2": 95.0,
        "year_built": 1890,
        "condition": PropertyCondition.major_renovation,
        "distance_to_station_km": 28.0,
        "distance_to_convenience_store_km": 22.0,
        "has_akiya_bank_listing": True,
        "akiya_bank_url": "https://tokushima-akiya.jp/",
        "municipal_subsidy_jpy": 2_000_000,
        "tags": ["thatched_roof", "iya_valley", "vine_bridge_nearby", "remote", "dramatic_scenery", "mountain_village"],
        "description": "日本三大秘境のひとつ・祖谷渓の絶景が望める茅葺き古民家。かずら橋まで車5分。世界的に注目される秘境エリアで民泊需要が急増中。（現在予約済み）",
        "notes": "現在別の申込者と協議中。キャンセル待ち登録可。",
        "latitude": 33.8667,
        "longitude": 133.6333,
        "population_decline_pct": 72.4,
    },
    # ─── NIIGATA (新潟) ──────────────────────────────────────────────────────
    {
        "title_jp": "越後の雪国古民家 - 十日町市",
        "title_en": "Snow Country Kominka in Tokamachi",
        "prefecture": "新潟県",
        "municipality": "十日町市",
        "village_name": "松代",
        "property_type": PropertyType.kominka,
        "status": PropertyStatus.available,
        "price_jpy": 1_500_000,
        "land_area_m2": 760.0,
        "building_area_m2": 200.0,
        "year_built": 1920,
        "condition": PropertyCondition.renovation_needed,
        "distance_to_station_km": 8.0,
        "distance_to_convenience_store_km": 4.0,
        "has_akiya_bank_listing": True,
        "akiya_bank_url": "https://niigata-akiya.jp/",
        "municipal_subsidy_jpy": 1_800_000,
        "tags": ["snow_country", "echigo_tsumari_art", "large_kominka", "traditional_architecture", "sakura_viewing", "terraced_fields"],
        "description": "越後妻有アートトリエンナーレのメイン会場に近い雪国古民家。豪雪地帯特有の「雁木」造り。大地の芸術祭のアーティスト・インレジデンスとして活用実績あるエリア。",
        "notes": "冬季融雪システム（屋根）あり。断熱改修を強く推奨。",
        "latitude": 37.1333,
        "longitude": 138.7500,
        "population_decline_pct": 40.2,
    },
    # ─── TOTTORI (鳥取) ──────────────────────────────────────────────────────
    {
        "title_jp": "砂丘近くの空き家 - 岩美町",
        "title_en": "Akiya Near Tottori Sand Dunes, Iwami Town",
        "prefecture": "鳥取県",
        "municipality": "岩美町",
        "village_name": "岩井",
        "property_type": PropertyType.akiya,
        "status": PropertyStatus.available,
        "price_jpy": 2_000_000,
        "land_area_m2": 310.0,
        "building_area_m2": 95.0,
        "year_built": 1968,
        "condition": PropertyCondition.livable,
        "distance_to_station_km": 1.5,
        "distance_to_convenience_store_km": 0.8,
        "has_akiya_bank_listing": True,
        "akiya_bank_url": "https://tottori-akiya.jp/",
        "municipal_subsidy_jpy": 700_000,
        "tags": ["near_coast", "sand_dunes_access", "onsen_iwai", "livable_condition", "station_close"],
        "description": "岩井温泉の湯の里・岩美町の空き家。鳥取砂丘まで車15分。岩井温泉の外湯が徒歩圏内。山陰海岸ジオパーク沿いの自然豊かな環境。即入居可能なコンディション。",
        "notes": "2021年まで居住。水回りは問題なし。外壁塗装が必要。",
        "latitude": 35.5333,
        "longitude": 134.3500,
        "population_decline_pct": 28.6,
    },
    {
        "title_jp": "廃村寸前の集落 空き家",
        "title_en": "Near-Abandoned Village Akiya, Koge Town",
        "prefecture": "鳥取県",
        "municipality": "若桜町",
        "village_name": "角ヶ仙",
        "property_type": PropertyType.akiya,
        "status": PropertyStatus.available,
        "price_jpy": 0,
        "land_area_m2": 890.0,
        "building_area_m2": 112.0,
        "year_built": 1955,
        "condition": PropertyCondition.major_renovation,
        "distance_to_station_km": 14.0,
        "distance_to_convenience_store_km": 12.0,
        "has_akiya_bank_listing": False,
        "akiya_bank_url": None,
        "municipal_subsidy_jpy": 2_500_000,
        "tags": ["free_property", "mountain_village", "depopulated", "off_grid_potential", "chugoku_mountains"],
        "description": "現在居住者3世帯のみの集落。若桜鬼ヶ城山麓の山間地。若桜町は積極的な移住支援を行っており補助金制度が充実。SLで有名な若桜鉄道の終点・若桜駅まで車20分。",
        "notes": "上水道なし・井戸水使用。プロパンガス。集落に残る最後の空き家のひとつ。",
        "latitude": 35.3333,
        "longitude": 134.4000,
        "population_decline_pct": 78.9,
    },
    # ─── YAMAGUCHI (山口) ────────────────────────────────────────────────────
    {
        "title_jp": "漁村の海が見える古民家 - 萩市",
        "title_en": "Fishing Village Kominka with Sea View in Hagi",
        "prefecture": "山口県",
        "municipality": "萩市",
        "village_name": "越ヶ浜",
        "property_type": PropertyType.kominka,
        "status": PropertyStatus.available,
        "price_jpy": 3_200_000,
        "land_area_m2": 420.0,
        "building_area_m2": 115.0,
        "year_built": 1942,
        "condition": PropertyCondition.renovation_needed,
        "distance_to_station_km": 4.0,
        "distance_to_convenience_store_km": 2.0,
        "has_akiya_bank_listing": True,
        "akiya_bank_url": "https://yamaguchi-akiya.jp/",
        "municipal_subsidy_jpy": 1_000_000,
        "tags": ["sea_view", "fishing_village", "hagi_castle_nearby", "historic_town", "japan_sea", "fresh_seafood"],
        "description": "世界遺産・萩城下町に隣接する漁村集落の古民家。日本海と萩の白壁土塀の街並みを望む好立地。新鮮な萩の海産物（いか・のどぐろ）に囲まれた暮らし。萩市は移住支援に積極的。",
        "notes": "潮風による外壁の傷みあり。内部は状態良好。",
        "latitude": 34.4167,
        "longitude": 131.3833,
        "population_decline_pct": 31.5,
    },
    {
        "title_jp": "廃業した旅館 - 長門市湯本温泉",
        "title_en": "Former Ryokan in Nagato Yumoto Onsen",
        "prefecture": "山口県",
        "municipality": "長門市",
        "village_name": "湯本温泉",
        "property_type": PropertyType.kominka,
        "status": PropertyStatus.available,
        "price_jpy": 8_000_000,
        "land_area_m2": 580.0,
        "building_area_m2": 380.0,
        "year_built": 1950,
        "condition": PropertyCondition.renovation_needed,
        "distance_to_station_km": 0.5,
        "distance_to_convenience_store_km": 1.0,
        "has_akiya_bank_listing": True,
        "akiya_bank_url": "https://yamaguchi-akiya.jp/",
        "municipal_subsidy_jpy": 3_000_000,
        "tags": ["onsen_source", "former_ryokan", "river_view", "commercial_potential", "large_building", "station_close"],
        "description": "山口県を代表する温泉地・長門湯本温泉の廃業旅館。源泉権付き。音信川沿いの絶好のロケーション。近年リノベーションホテルが相次ぎ開業するエリア。小規模宿泊施設として再生したい事業者向け。",
        "notes": "温泉源泉の権利は別途継承手続きが必要。旅館業許可の取得サポートあり。",
        "latitude": 34.3667,
        "longitude": 131.2167,
        "population_decline_pct": 33.7,
    },
    # ─── BONUS: GIFU (岐阜) ─────────────────────────────────────────────────
    {
        "title_jp": "白川郷風の合掌造り - 東白川村",
        "title_en": "Gassho-Zukuri Farmhouse, Higashishirakawa Village",
        "prefecture": "岐阜県",
        "municipality": "東白川村",
        "village_name": "越原",
        "property_type": PropertyType.kominka,
        "status": PropertyStatus.available,
        "price_jpy": 5_000_000,
        "land_area_m2": 1100.0,
        "building_area_m2": 220.0,
        "year_built": 1880,
        "condition": PropertyCondition.major_renovation,
        "distance_to_station_km": 20.0,
        "distance_to_convenience_store_km": 8.0,
        "has_akiya_bank_listing": True,
        "akiya_bank_url": "https://gifu-akiya.jp/",
        "municipal_subsidy_jpy": 2_000_000,
        "tags": ["gassho_zukuri", "thatched_roof", "mountain_village", "traditional_architecture", "shirakawa_nearby", "cultural_asset_potential"],
        "description": "白川郷に隣接する東白川村の合掌造り古民家。非公認の世界遺産バッファゾーン。豪雪地帯の急勾配屋根が特徴。村の補助制度を活用したゲストハウス転用実績あり。名古屋から約1.5時間。",
        "notes": "合掌部の茅葺き修繕が急務。村の景観条例に従った改修が必要。",
        "latitude": 35.7000,
        "longitude": 137.2000,
        "population_decline_pct": 55.3,
    },
]


def seed_database():
    create_db_and_tables()

    with Session(engine) as session:
        existing = session.exec(select(Property)).first()
        if existing:
            print("Database already seeded. Skipping.")
            return

        print(f"Seeding {len(SEED_DATA)} akiya properties...")

        base_date = datetime.utcnow() - timedelta(days=60)
        for i, data in enumerate(SEED_DATA):
            tags = data.pop("tags", [])
            created = base_date + timedelta(days=i * 4)
            prop = Property(
                **data,
                created_at=created,
                updated_at=created,
            )
            prop.tags = tags
            session.add(prop)

        session.commit()
        print(f"✅ Seeded {len(SEED_DATA)} properties successfully.")
        print("\nPrefecture breakdown:")
        prefectures = {}
        for d in SEED_DATA:
            pref = d.get("prefecture", "")
            prefectures[pref] = prefectures.get(pref, 0) + 1
        for pref, count in sorted(prefectures.items()):
            print(f"  {pref}: {count} properties")


if __name__ == "__main__":
    seed_database()
